### ISSUE TITLE
Make right-aligned blocks grow on left

### ISSUE THREAD

**Issue by Anachron** [geommer/yabar#1]
If I add more blocks to the right part, wouldn't it be more useful to show them on the left?
This way first block gets first priority.

Edit: Maybe this could be an optional setting.

**Comment by geommer** [comment]
If I understand you correctly, yabar currently processes the blocks consecutively or right to each other just as stated in the `block-list` entry. So if your `block-list = [blk1,blk2, blk3]` and they are all right-aligned, thus what should be shown on screen is as follows
-----------------------------------
                  blk1 | blk2 | blk3
-----------------------------------

Actually yabar walks the whole block-list without walking left blocks first, then center blocks then right blocks. And thus, every new block is drawn right to its predecessor block of its designated alignment.

**Comment by Anachron** [comment]
@geommer exactly, and I would like to have the ability to switch this, so those blocks that are in the right area, blk1 will actually be the most right one, blk2 left of it and alike.

**Comment by geommer** [comment]
@Anachron I could do what you want but frankly it may disturb other users because the left and center alignments would work the opposite way to the right alignment. Besides, most of yabar targeted users will migrate from lemonbar and i3blocks which I think both work that way. Is there a program that works the way you seek?

**Comment by Anachron** [comment]
I'm not sure where I have this from, but both from Windows and Linux I had panels which were acting that way.

This will be optional and non-default, of course, so it wont break the current implementation.

**Comment by huffstler** [comment]
@Anachron maybe I'm not understanding what you mean correctly, but (using @geommer's example) couldn't you set up the config like so?

`block-list: {"blk3", "blk2", "blk1"}`

Blocks grow to the right so they should appear like this:

`blk3 | blk2 | blk1`

This way the blocks would be in the orientation that you desire, since they grow to the right and @geommer wouldn't need to code in an extra feature.

**Comment by Anachron** [comment]
Yes but it is last-come, first-serve then. I like first-come, first-serve.

So in this scenario, whatever I add first should be most right and so top priority.

**Comment by huffstler** [comment]
Alright, well this will be my last comment on this issue as I don't want to needlessly muck up the devs notification feed.

It seems to me that the need to add a FIFO structure that was designed to be a LIFO structure is unecessary, especially when you can easily reverse your input and get the desired results, BUT that's just my opinion.
