### ISSUE TITLE
issue with mpc

### ISSUE THREAD

**Issue by 676339784** [geommer/yabar#107]
Yabar updates my music block completely fine, but after clearing my playlist or when mpd stops playback and I add songs after and start to play, tracks are no longer updated in yabar. Thus, I would have to run yabar which fixes the issue until I reach the end of the playlist and decide to add more songs and then the issue repeats, etc.

[Here](https://gist.github.com/676339784/6a30e298f9d22797a67a754e5041bfd1) is my music block in yabar, for reference.

**Comment by jacksgt** [comment]
Are you sure this is an issue with yabar, rather than the mpc?
I.e. have you manually verified the output of `mpc current` when this glitch happens?

**Comment by 676339784** [comment]
Yes, mpc current returns the correct things.

**Comment by 676339784** [comment]
@jacksgt [Example](https://u.sicp.me/d2dLg.png)

**Comment by pjhalsli** [comment]
I had the same problem so now I'm just using /path/to/mpcscript.   Have not encountered the same issue since

this is my block now
 mpc: {
	exec:"~/.config/yabar/scripts/music";
	internal-prefix: "♫";
	align: "right";
	fixed-size: 450;
	type: "periodic";
	interval: 1;
	underline-color-rgb:0xff5555;
	foreground-color-rgb:0x111313;
        background-color-rgb:0x555555;
        variable-size: true

and the sctipt I use

#!/bin/bash
status=`mpc status | awk '{ if (NR==2) print $1}' | tr -d '[]'`
music=`mpc status | awk '{if (NR==1) print}'`
if [ $status == "playing" ]
then
    echo "            $music      "
elif [ $status == "paused" ]
then
	echo "            $music      "
else
	echo ""
fi

no more problem - been using this for months now withou any issues

**Comment by 676339784** [comment]
@pjhalsli Greatly appreciated: this works!

**Comment by pjhalsli** [comment]
@pjhalsli 
Glad to help   :)
