### ISSUE TITLE
Pass positional information to button press commands

### ISSUE THREAD

**Issue by Lindenk** [geommer/yabar#13]
By giving scripts a block position on the screen to work with, they can more accurately place new windows and whatnot rather than relying on the cursor position after the event.

For example, a small window containing a calendar might be positioned directly above, and aligned with, a date block when clicked. Without knowing the position and dimensions of the block, the calendar would be difficult to position accurately and consistently.

I propose the environment variables `$YABAR_BLOCK_X`, `$YABAR_BLOCK_Y`, `$YABAR_BLOCK_WIDTH`, and `$YABAR_BLOCK_HEIGHT`, relative to the screen, should be set to the clicked block's position and size when running a command using `command-button#`.

**Comment by geommer** [comment]
@Lindenk thank you for this. I think I just made what you want but I really would like to see what tools would benefit from this (I tried to test it using a tool named `maim` but it was just a meaningless test). I added `$YABAR_BLOCK_X`, `$YABAR_BLOCK_Y`, `$YABAR_BLOCK_WIDTH` because `$YABAR_BLOCK_HEIGHT` is the same as the bar height. X and Y env variables are currently the absolute values on the screen.

**Comment by geommer** [comment]
I changed `YABAR_BLOCK_X` to be always the start absolute x of the block instead of the exact press position. Also `YABAR_BLOCK_Y` is the absolute y position just below the block in case of top bar or just above the block in case of bottom bar. This, I guess, makes more sense to draw your window-on-button-press just below or above the bar and consequently not drawing it inside yabar area.

**Comment by Lindenk** [comment]
Sweet. That looks like exactly what I was thinking. Some of the inspiration for the idea came from configurations for calendars or volume sliders that appeared when a block was clicked on (for example, [this calendar made with dzen2](https://urukrama.files.wordpress.com/2008/05/dzen_pypanel.png))
