### ISSUE TITLE
wrong battery information

### ISSUE THREAD

**Issue by merrickluo** [geommer/yabar#157]
I'm using XPS15, I notice my battery is at 103%,  I searched in code and see `/sys/class/power_supply/BAT0/capacity`
```
 »»»» cat /sys/class/power_supply/BAT0/capacity
103
```
After google I find another way to retrieve battery info 
https://askubuntu.com/questions/69556/how-to-check-battery-status-using-terminal
and this is my output 
```
 »»»» upower -i /org/freedesktop/UPower/devices/battery_BAT0                 
  native-path:          BAT0
  vendor:               SMP
  model:                DELL 1P6KD54
  serial:               550
  power supply:         yes
  updated:              Fri 21 Jul 2017 04:27:04 PM HKT (79 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    energy:              83.9952 Wh
    energy-empty:        0 Wh
    energy-full:         83.9952 Wh
    energy-full-design:  83.9952 Wh
    energy-rate:         0.0114 W
    voltage:             12.786 V
    percentage:          100%
    capacity:            96.4848%
    technology:          lithium-polymer
    icon-name:          'battery-full-charged-symbolic'
```
I think we should change to this method instead?
Also, thanks for the great project. 😄

**Comment by Narrat** [comment]
Which should be added as a new dependency then, because not everyone has upower installed (not me at least :D and looking at the package details of upower from my used distro, it will only be installed if someone explicitly installs it or is using one of the DEs (Gnome, KDE, XFCE, Cinnamon) were panels are present)
Imo it would be simpler to check if the value from `/sys/class/power_supply/BAT0/capacity` is greater than 100 and simply cap it to that value?
Would be interesting to see what upower is doing

**Comment by merrickluo** [comment]
Yeah, I think cap to 100 is also a good idea...

**Comment by NBonaparte** [comment]
From what I've seen in upower they also clamp the battery from 0 to 100, so I think this is the best solution here.
