### ISSUE TITLE
BUFFSIZE is too small for scripts outputting complex markup

### ISSUE THREAD

**Issue by vlaci** [geommer/yabar#29]
512 character limit can be too low for a status block containing lots of pango formatting

**Comment by geommer** [comment]
Hi @vlaci, and thanks to @Lindenk for the small patch. I am aware that 512 byte-buffers may not be sufficient to store the text especially for the case when `pango-markup: true`. The problem is that after every text drawing operation, the entire buffer gets zeroed using `memset()`. I am not sure about the impact if we increase it to 4096 especially when most blocks won't even exceed 100 bytes.

**Comment by Lindenk** [comment]
I've modifed #33 to no longer call memset on block buffers and instead append a `\0` to the end of the output of the command. Also, after thinking about it, it looks like `memset` would have only gotten called only once each time a script outputs something, which would most likely only be once every couple of seconds.

**Comment by geommer** [comment]
Thank you @Lindenk, I think this is better now, the only issue of me here is that 4096 is too large. If we try to make the buffer a pointer to a dynamically allocated memory instead of being statically allocated, does that make it more performant? I mean does the kernel really allocate and zeroes an entire big buffer when you command it to do?

**Comment by vlaci** [comment]
Thank you! Works much better now :+1:
