### ISSUE TITLE
Experiencing crashes

### ISSUE THREAD

**Issue by TingoL** [geommer/yabar#54]
I've been having yabar crash on me a couple of times in the last few days. I'm not really sure what the reason is. Mostly it's just core dumped on some random event. Here's the output I've gotten the last time it happened. http://pastebin.com/KCcHCrD4

FYI, I'm using 
 * FrankenWM (a minimal dwm fork)
 * Yabar 0.4.0-2 
 * Arch Linux

**Comment by geommer** [comment]
Thank you @TingoL, I have experienced this a few times throughout the last two weeks (since 0.4 as you use stable) too. I strongly think this bug is related to some internal block. Do you use internal blocks? If so, what are they? If you paste your `yabar.conf` file, that would be more helpful to me.

**Comment by TingoL** [comment]
@geommer Sure here it is: http://pastebin.com/Bh4JYBEx

**Comment by TingoL** [comment]
Just a quick update, after I removed CPU and MEM blocks the crashes completely stopped so I think the problem might be related to one of those two.

**Comment by geommer** [comment]
Thank you @TingoL, are you still using yabar 0.4 from AUR or you switched to the git version? I still doubt this bug could be related to YABAR_TITLE internal block even after I fixed a potential illegal buffer access after you opened the issue for this block.

**Comment by z1lt0id** [comment]
I too have been having this issue where it would randomly crash numerous times throughout the day.  Not sure if there is any easy way to debug Yabar - does it have a log file - if not that would be a good feature.  Anywhere here is my config to see if you can find similar routines that might cause the crash.

http://dpaste.com/231BDZE

**Comment by geommer** [comment]
Hi guys! since I have been using the branch `dev_var_width` for the last 3 or 4 weeks to develop a more consistent and robust variable-width feature, I also happened to fix some small bugs. I now don't experience those several crashes in the `master` branch. The internal block `YABAR_TITLE` still causes a crash on a very rare case which I don't understand (closing firefox with betterprivacy addon invoking its popup window). So using `xtitle` instead `YABAR_TITLE` fixes this for now.

I hope I can have the time to finish developing `dev_var_width` and merge it into `master` very soon.

**Comment by TingoL** [comment]
Sorry for the lack of feedback, I've dropped the title block and all the instability stopped. I don't have plans to use it again but I can test it when it hits master and post the results.

**Comment by HellishINC** [comment]
If using `YABAR_TITLE`, launching Steam will always crash yabar.

**Comment by geommer** [comment]
Hi guys, I know this is too late. But I think the bug is now fixed thanks to the contribution #69 by @abarbu. Please pull the latest commit and rebuild yabar source.

**Comment by TingoL** [comment]
Using it for the last couple of days and all seems good. No more crashes with the title block.
