### ISSUE TITLE
bspwm workspaces

### ISSUE THREAD

**Issue by z1lt0id** [geommer/yabar#7]
Hi was wondering if you have implemented a way to incorporate bspwm workspaces into Yabar? Couldn't see anything in the documentation.

**Comment by geommer** [comment]
Yabar is wm-agnostic. Adding bspwm workspaces can be added using a script just like in lemonbar. I myself use bspwm and I think I may create a scripts folder that contains some scripts for generic uses. However I don't have that particular script so far but I intend to make a one very soon.

**Comment by z1lt0id** [comment]
Out of curiosity how would you adapt the following:
[original workspace code](https://bpaste.net/show/a5a54b89733e)

**Comment by geommer** [comment]
@z1lt0id I made a fast and untidy fix for your script in order to work on yabar.
https://bpaste.net/show/2e1276b6ea1d

make sure that you have the block options
`type: "persist";` and `pango-markup: true;`
I think it would be much better to make the bspwm workspaces script based on bspc --subscribe combined with sed/awk black magic.

**Comment by z1lt0id** [comment]
@geommer thanks i'll look into this today :)
