### ISSUE TITLE
blocks with pipes in exec with type: "persist" fail

### ISSUE THREAD

**Issue by ronaldscott** [geommer/yabar#75]
For example, I use bspwm. One can use `bspc subscribe desktop_focus` to have a persistent process that returns desktop focus events in the form `desktop_focus <monitor-name> <desktop-name>`. 

A block like...
```
workspace:{
    exec: "bspc subscribe desktop_focus";
    align: "left";
    fixed-size: 500;
    type: "persist";
}
```
...works just fine, and the block will persistently be updated with the currently focused desktop.

However this output is ugly, and I'd like to format it like `bspc subscribe desktop_focus | cut -d ' ' -f 3`. Running this from the terminal works just fine; changing desktops results in a string of various desktop names echoing to the terminal. But updating the previous config to...
```
workspace:{
    exec: "bspc subscribe desktop_focus | cut -d ' ' -f 3";
    align: "left";
    fixed-size: 500;
    type: "persist";
}
```
...fails silently with an empty block. I have tried various strategies, such as putting the exec in a shell script, using other text-processing programs like sed and awk, and all fail silently.

**Comment by ronaldscott** [comment]
Solved, thanks to [this Arch BBS post by stupidus](https://bbs.archlinux.org/viewtopic.php?pid=1620447#p1620447) and [this Stack Exchange](http://unix.stackexchange.com/questions/25372/turn-off-buffering-in-pipe). `cut` is doing output buffering which must be deactivated. The following config works:
workspace:{
    exec: "bspc subscribe desktop_focus | stdbuf -oL -eL cut -d ' ' -f 3";
    align: "left";
    fixed-size: 500;
    type: "persist";
}
It's probably less unsightly to put the command in a shell script at this point.

I think you should consider writing up the output buffering issue in your README.

Closed.

**Comment by elGatoMantocko** [comment]
I am not sure if this is solved. Using i3 and have a similar (but a bit more complicated) command:
```
exec: "i3-msg -t get_workspaces | jq '.[] | select(.focused == true) | .name' | tr -d \" | awk '{print $2}'";
type: "periodic";
interval: 1;
...
```
This command should output a single double wide glyph that signifies the current workspace. I tried changing it to something like this:
```
exec: "i3-msg -t get_workspaces | stdbuf -oL -eL jq '.[]  | select(.focused == true) | .name' | stdbuf -oL -eL awk '{print $2}'";
type: "persist";
...
```
but that doesn't work. The block won't update when the workspace character changes.
I currently use the xtitle -s command as my title block which has the persist type, so I know that it works for single commands. I wondered if it's just because yabar has trouble escaping characters, but this wasn't the case because I just dumped the command into a script and it had the same behavior.

This appears that it could be a deeper issue. I would love to have some follow up to this and maybe even look at the code to see what could be done to fix it.

P.S. Probably a little off topic of discussion but I have definitely noticed that certain characters (like double quote for example) can't be escaped in the exec line. Maybe that should either be documented or an added ability.
